server:
  port: 8034
spring:
  application:
    name: eshop-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
api:
  prefix: api/v1
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
